-- Adds Locations and mandatory implement.location_id
-- Safe to run in existing environments (idempotent where possible).

-- 1) Create location table (if missing)
CREATE TABLE IF NOT EXISTS public.location
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    description VARCHAR(200)
);

-- 2) Ensure at least one default location exists (used to backfill existing implements)
INSERT INTO public.location (name, description)
SELECT 'Por definir', 'Ubicacion pendiente'
WHERE NOT EXISTS (SELECT 1 FROM public.location);

-- 3) Add implement.location_id (if missing)
ALTER TABLE public.implement
    ADD COLUMN IF NOT EXISTS location_id INTEGER;

-- 4) Backfill existing implements (if any)
UPDATE public.implement i
SET location_id = (SELECT l.id FROM public.location l ORDER BY l.id ASC LIMIT 1)
WHERE i.location_id IS NULL;

-- 5) Enforce NOT NULL (mandatory location)
ALTER TABLE public.implement
    ALTER COLUMN location_id SET NOT NULL;

-- 6) Add FK (if missing)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'implement_location_fk'
    ) THEN
        ALTER TABLE public.implement
            ADD CONSTRAINT implement_location_fk
                FOREIGN KEY (location_id)
                    REFERENCES public.location (id)
                    ON DELETE RESTRICT;
    END IF;
END $$;

